"""
HYPERION Image Processor — Pillow pipeline for print-quality PDF images.

Every image — whether from Unsplash or generated by Plotly — goes through
the same Pillow pipeline before being placed in the PDF. This is NOT a
generic "resize an image" wrapper. It implements the exact 6-step pipeline
from ARCHITECTURE.md §6.4:

1. Open and verify image is high enough resolution
2. Resize (downscale only, never upscale — if too small, raise error)
3. Crop (center-weighted, preserving most visually interesting region)
4. Color-correct (match brand warmth — slightly warm, not cold/blue)
5. Sharpen (unsharp mask for print clarity)
6. Export as PNG (lossless, 300 DPI)

The warm filter is critical — it makes images feel premium and consistent
with the HYPERION palette. Cold/blue images look like generic AI output.

Architecture reference: §6.4 — "Every image — whether from Unsplash or
generated by Plotly — goes through the same Pillow pipeline before being
placed in the PDF."

§6.3 rule 4: "All images processed through Pillow pipeline:
- Resize (never upscale — if image is too small, find a different one)
- Crop (center-weighted, preserving the most visually interesting region)
- Color-correct (match brand warmth — slightly warm, not cold/blue)
- Sharpen (unsharp mask for print clarity)
- Export as PNG (lossless, 300 DPI equivalent)"

Used by: Render Engine (PILLOW tool), Data Visualizer (PILLOW tool) (§5.1)
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


class ImageTooSmallError(Exception):
    """Raised when an image is smaller than the target dimensions.

    Per §6.3 rule 4: "never upscale — if image is too small, find a
    different one." This error tells the caller to search for a
    higher-resolution image.
    """


@dataclass
class ImageProcessResult:
    """Result of processing an image through the Pillow pipeline."""

    input_path: str
    output_path: str = ""
    original_width: int = 0
    original_height: int = 0
    target_width: int = 0
    target_height: int = 0
    final_width: int = 0
    final_height: int = 0
    dpi: int = 300
    warmed: bool = False
    sharpened: bool = False
    cropped: bool = False
    error: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "input_path": self.input_path,
            "output_path": self.output_path,
            "original_width": self.original_width,
            "original_height": self.original_height,
            "target_width": self.target_width,
            "target_height": self.target_height,
            "final_width": self.final_width,
            "final_height": self.final_height,
            "dpi": self.dpi,
            "warmed": self.warmed,
            "sharpened": self.sharpened,
            "cropped": self.cropped,
            "error": self.error,
        }


class ImageProcessor:
    """Pillow image processing pipeline for print-quality PDF.

    Implements the exact 6-step pipeline from §6.4:
    1. Verify resolution (never upscale)
    2. Resize (LANCZOS — best quality downscale)
    3. Crop (center-weighted)
    4. Color-correct (warm filter, intensity=0.05)
    5. Sharpen (UnsharpMask radius=2, percent=150, threshold=3)
    6. Export PNG at 300 DPI

    Usage:
        processor = ImageProcessor(settings=settings)
        result = processor.process_image(
            image_path="assets/images/cover.jpg",
            target_width=1920,
            target_height=1080,
        )
        print(f"Processed: {result.output_path}")
    """

    # Pipeline parameters (§6.4 — exact values from architecture)
    WARM_FILTER_INTENSITY = 0.05  # Slightly warm, not cold/blue
    SHARPEN_RADIUS = 2
    SHARPEN_PERCENT = 150
    SHARPEN_THRESHOLD = 3
    EXPORT_DPI = 300
    OUTPUT_FORMAT = "PNG"

    # Target sizes for common image placements (§6.3)
    COVER_WIDTH = 1920
    COVER_HEIGHT = 1080
    SECTION_HEADER_WIDTH = 800
    SECTION_HEADER_HEIGHT = 400
    CHART_WIDTH = 1200
    CHART_HEIGHT = 800

    def __init__(self, settings: Any | None = None) -> None:
        self.settings = settings
        self._output_dir = Path("assets/images/processed")
        if settings:
            self._output_dir = Path(getattr(settings, "assets_dir", "assets")) / "images" / "processed"
        self._output_dir.mkdir(parents=True, exist_ok=True)

    def _import_pillow(self) -> tuple[Any, Any, Any]:
        """Import Pillow components. Returns (Image, ImageFilter, ImageEnhance)."""
        from PIL import Image, ImageFilter, ImageEnhance

        return Image, ImageFilter, ImageEnhance

    def apply_warm_filter(self, img: Any, intensity: float = WARM_FILTER_INTENSITY) -> Any:
        """Apply a warm color filter to match brand warmth.

        This makes images feel premium and consistent with the HYPERION
        palette. Cold/blue images look like generic AI output.

        The filter:
        - Increases red channel slightly
        - Decreases blue channel slightly
        - Adds a subtle warm overlay

        Args:
            img: PIL Image object
            intensity: Filter strength (0.0 = none, 1.0 = full)

        Returns:
            Filtered PIL Image.
        """
        Image, ImageFilter, ImageEnhance = self._import_pillow()

        # Convert to RGB if necessary
        if img.mode != "RGB":
            img = img.convert("RGB")

        # Increase warmth by boosting red and reducing blue
        r, g, b = img.split()

        # Boost red channel
        r_enhancer = ImageEnhance.Brightness(r)
        r = r_enhancer.enhance(1.0 + intensity)

        # Reduce blue channel
        b_enhancer = ImageEnhance.Brightness(b)
        b = b_enhancer.enhance(1.0 - intensity * 0.7)

        # Slightly boost green for natural warmth
        g_enhancer = ImageEnhance.Brightness(g)
        g = g_enhancer.enhance(1.0 + intensity * 0.3)

        return Image.merge("RGB", (r, g, b))

    def center_crop(self, img: Any, target_width: int, target_height: int) -> Any:
        """Center-weighted crop preserving the most visually interesting region.

        Crops from the center of the image, maintaining the target aspect
        ratio. If the image is already the right ratio, no crop needed.

        Args:
            img: PIL Image object
            target_width: Target width in pixels
            target_height: Target height in pixels

        Returns:
            Cropped PIL Image.
        """
        orig_width, orig_height = img.size
        target_ratio = target_width / target_height
        orig_ratio = orig_width / orig_height

        if orig_ratio > target_ratio:
            # Image is wider than target — crop width
            new_width = int(orig_height * target_ratio)
            left = (orig_width - new_width) // 2
            return img.crop((left, 0, left + new_width, orig_height))
        elif orig_ratio < target_ratio:
            # Image is taller than target — crop height
            new_height = int(orig_width / target_ratio)
            top = (orig_height - new_height) // 2
            return img.crop((0, top, orig_width, top + new_height))
        else:
            # Already the right ratio — no crop needed
            return img

    def process_image(
        self,
        image_path: str,
        target_width: int,
        target_height: int,
        warm_filter: bool = True,
        sharpen: bool = True,
        output_path: str = "",
    ) -> ImageProcessResult:
        """Process an image through the full Pillow pipeline.

        This is the main entry point. Implements the exact 6-step pipeline
        from §6.4.

        Args:
            image_path: Path to the input image
            target_width: Target width in pixels
            target_height: Target height in pixels
            warm_filter: Whether to apply the warm color filter
            sharpen: Whether to apply the unsharp mask
            output_path: Custom output path. If empty, auto-generated.

        Returns:
            ImageProcessResult with processing details.

        Raises:
            ImageTooSmallError: If the image is smaller than target dimensions.
            FileNotFoundError: If the input image doesn't exist.
        """
        Image, ImageFilter, ImageEnhance = self._import_pillow()

        result = ImageProcessResult(
            input_path=image_path,
            target_width=target_width,
            target_height=target_height,
        )

        # Step 1: Open and verify resolution
        try:
            img = Image.open(image_path)
        except (OSError, ValueError) as e:
            result.error = f"Failed to open image: {e}"
            return result

        result.original_width = img.width
        result.original_height = img.height

        # Verify resolution — never upscale (§6.3 rule 4)
        if img.width < target_width or img.height < target_height:
            raise ImageTooSmallError(
                f"Image {img.width}x{img.height} < target {target_width}x{target_height}. "
                f"Find a higher-resolution image. Never upscale."
            )

        # Convert to RGB if necessary (for consistent processing)
        if img.mode not in ("RGB", "RGBA"):
            img = img.convert("RGB")

        # Step 2: Resize (downscale only, LANCZOS for best quality)
        img = img.resize((target_width, target_height), Image.LANCZOS)

        # Step 3: Crop (center-weighted)
        # After resize, the image is exactly target size, so crop is only
        # needed if we resized to a different aspect ratio
        img = self.center_crop(img, target_width, target_height)
        result.cropped = True

        # Step 4: Color-correct (match brand warmth)
        if warm_filter:
            img = self.apply_warm_filter(img, intensity=self.WARM_FILTER_INTENSITY)
            result.warmed = True

        # Step 5: Sharpen (unsharp mask for print clarity)
        if sharpen:
            img = img.filter(
                ImageFilter.UnsharpMask(
                    radius=self.SHARPEN_RADIUS,
                    percent=self.SHARPEN_PERCENT,
                    threshold=self.SHARPEN_THRESHOLD,
                )
            )
            result.sharpened = True

        # Step 6: Export as PNG (lossless, 300 DPI)
        if not output_path:
            # Auto-generate output path
            input_name = Path(image_path).stem
            output_path = str(self._output_dir / f"{input_name}_processed.png")

        img.save(output_path, self.OUTPUT_FORMAT, dpi=(self.EXPORT_DPI, self.EXPORT_DPI))

        result.output_path = output_path
        result.final_width = img.width
        result.final_height = img.height
        result.dpi = self.EXPORT_DPI

        return result

    def process_cover_image(
        self,
        image_path: str,
        output_path: str = "",
    ) -> ImageProcessResult:
        """Process a cover image (full-bleed, 1920x1080).

        Cover images are the visual statement of the report. They get
        the full pipeline treatment with the largest target dimensions.
        (§6.3 rule 2: "Cover image = full-bleed.")
        """
        return self.process_image(
            image_path=image_path,
            target_width=self.COVER_WIDTH,
            target_height=self.COVER_HEIGHT,
            output_path=output_path,
        )

    def process_section_image(
        self,
        image_path: str,
        output_path: str = "",
    ) -> ImageProcessResult:
        """Process a section header image (40% page width, 800x400).

        Section images are smaller than cover images and placed at 40%
        page width, right-aligned, with caption below.
        (§6.3 rule 2: "Section images = 40% page width, right-aligned.")
        """
        return self.process_image(
            image_path=image_path,
            target_width=self.SECTION_HEADER_WIDTH,
            target_height=self.SECTION_HEADER_HEIGHT,
            output_path=output_path,
        )

    def process_chart_image(
        self,
        image_path: str,
        output_path: str = "",
    ) -> ImageProcessResult:
        """Post-process a Plotly chart image (sharpen for print).

        Charts are already PNG from Plotly at scale=3, but they still
        go through the sharpen step for print clarity. The warm filter
        is NOT applied to charts — they already use brand colors.
        (§6.3 rule 5: "Charts are NEVER screenshots. Always Plotly →
        kaleido → PNG at scale=3.")
        """
        return self.process_image(
            image_path=image_path,
            target_width=self.CHART_WIDTH,
            target_height=self.CHART_HEIGHT,
            warm_filter=False,  # Charts already use brand colors
            sharpen=True,  # Still sharpen for print
            output_path=output_path,
        )

    def verify_resolution(
        self,
        image_path: str,
        min_width: int,
        min_height: int,
    ) -> bool:
        """Verify that an image meets minimum resolution requirements.

        Used before processing to check if an image is high enough
        resolution. Returns True if the image is large enough.
        """
        Image, _, _ = self._import_pillow()

        try:
            with Image.open(image_path) as img:
                return img.width >= min_width and img.height >= min_height
        except (OSError, ValueError):
            return False

    def get_image_info(self, image_path: str) -> dict[str, Any]:
        """Get metadata about an image without processing it.

        Returns width, height, mode, format, and DPI info.
        """
        Image, _, _ = self._import_pillow()

        try:
            with Image.open(image_path) as img:
                dpi = img.info.get("dpi", (0, 0))
                return {
                    "path": image_path,
                    "width": img.width,
                    "height": img.height,
                    "mode": img.mode,
                    "format": img.format or "",
                    "dpi": dpi[0] if isinstance(dpi, tuple) else 0,
                }
        except (OSError, ValueError) as e:
            return {"path": image_path, "error": str(e)}

    async def close(self) -> None:
        """Close any open resources."""
        pass

    async def __aenter__(self) -> ImageProcessor:
        return self

    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        await self.close()
